<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>UTS.Infrastructure.SQLite</RootNamespace>
    <AssemblyName>UTS.Infrastructure.SQLite</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\UTS.Core\UTS.Core.vbproj" />
    <ProjectReference Include="..\UTS.Application.Contracts\UTS.Application.Contracts.vbproj" />
    <PackageReference Include="System.Data.SQLite.Core" />
  </ItemGroup>
</Project>
