<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>UTS.Core.Tests</RootNamespace>
    <AssemblyName>UTS.Core.Tests</AssemblyName>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\UTS.Core\UTS.Core.vbproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" PrivateAssets="all" />
  </ItemGroup>
</Project>
